const P=window.PODCASTS||[],META=window.PODCAST_META||{},K='soheilPodcastAtlasV4',BUILD='10.1';
let U=JSON.parse(localStorage.getItem(K)||'{}'),tag='';
const $=x=>document.getElementById(x),S=id=>U[id]||{favorite:false,listened:false,progress:0,note:''};
function save(){localStorage.setItem(K,JSON.stringify(U));stats()}
function set(id,p){U[id]={...S(id),...p};save();render();paths();next()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function stats(){let s=P.map(p=>S(p.id));$('total').textContent=P.length;$('favN').textContent=s.filter(x=>x.favorite).length;$('doneN').textContent=s.filter(x=>x.listened||x.progress===100).length;$('avgN').textContent=Math.round(s.reduce((a,x)=>a+(x.progress||0),0)/Math.max(1,s.length))+'%'}
function artUrl(p){let u=String((META[p.id]||{}).image||'').replace(/^http:/,'https:');if(!u)return'';return u+(u.includes('?')?'&':'?')+'v='+BUILD}
function artMarkup(p,cls='',alt=true){let a=artUrl(p),fallback=esc(p.icon||'🎙️');return `<div class="coverFallback">${fallback}</div>${a?`<img class="${cls}" src="${esc(a)}" alt="${alt?esc(p.title):''}" loading="eager" decoding="async" hidden onload="this.hidden=false;this.previousElementSibling.hidden=true;this.dataset.loaded='1'" onerror="this.hidden=true;this.previousElementSibling.hidden=false">`:''}`}
function sourceBlock(p,fa){let m=META[p.id]||{},d=m.description||p.desc||'',name=m.sourceName||'Podcast catalogue',u=m.sourceUrl||p.url;return `<details class="sourceDesc"><summary>${fa?'توضیحات کانال از منبع':'Channel description from source'} <span>${esc(name)}</span></summary><p>${esc(d)}</p>${u?`<a target="_blank" rel="noopener" href="${esc(u)}">${fa?'مشاهده منبع':'View source'} ↗</a>`:''}</details>`}
function next(){let x=P.map(p=>({p,s:S(p.id)})).filter(x=>!x.s.listened&&x.s.progress<100).sort((a,b)=>(b.p.score+(b.s.favorite?30:0)+b.s.progress)-(a.p.score+(a.s.favorite?30:0)+a.s.progress))[0];if(!x){$('next').innerHTML='همه موارد تکمیل شده‌اند.';return}let lc=x.p.lang==='فارسی'?'lang-fa':'lang-en';$('next').className='next '+lc;$('next').innerHTML=`<div class="nextArt">${artMarkup(x.p,'',false)}</div><div><b>${esc(x.p.title)}</b><br><span>${esc(x.p.category)} • ${x.p.score}% Match • ${x.s.progress}% پیشرفت</span><br><a target="_blank" rel="noopener" href="${esc(x.p.url)}">باز کردن پادکست</a></div>`}
const L=[['Cyber & Microsoft Security','🛡️'],['Maker Lab','🔧'],['Stories & Fiction','📖'],['True Crime','🕵️'],['Music Journey','🎵'],['AI & Future Tech','🤖']];
function paths(){$('paths').innerHTML=L.map(([n,i])=>{let a=P.filter(p=>p.learningPath===n),v=a.length?Math.round(a.reduce((z,p)=>z+(S(p.id).progress||0),0)/a.length):0;return `<div class="path" onclick="filterPath('${n}')"><span style="font-size:25px">${i}</span><strong>${n}</strong><small>${a.length} پادکست • ${v}%</small><div class="bar"><i style="width:${v}%"></i></div></div>`}).join('')}
function filterPath(n){$('q').value=n;tag='';render();$('library').scrollIntoView({behavior:'smooth'})}
const CATS=[['Cybersecurity','🛡️','Cybersecurity & Cloud'],['Electronics','⚡','Electronics & Maker'],['3D Printing','🖨️','3D Printing'],['Storytelling','📚','Stories & Fiction'],['True Crime','🕵️','True Crime'],['Music','🎸','Music'],['Microsoft','☁️','Microsoft'],['AI','🤖','AI & Future Tech']];
function categories(){$('categoryTiles').innerHTML=CATS.map(([t,i,n],k)=>`<div class="categoryTile ct${k%6}" data-icon="${i}" onclick="pickTag('${t}')"><strong>${n}</strong><small>${P.filter(p=>(p.tags||[]).includes(t)).length} انتخاب</small></div>`).join('')}
function pickTag(t){tag=t;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.t===t));render();$('library').scrollIntoView({behavior:'smooth'})}
function featureCard(p){let lc=p.lang==='فارسی'?'lang-fa':'lang-en';return `<a class="featureCard ${lc}" target="_blank" rel="noopener" href="${esc(p.url)}"><span class="langFlag">${p.lang==='فارسی'?'FA':'EN'}</span><div class="featureArtWrap">${artMarkup(p,'featureArt')}</div><div class="featureMeta"><strong>${esc(p.title)}</strong><small>${esc(p.category)} • ${p.score}%</small></div></a>`}
function featured(shuffle=false){let a=P.filter(p=>p.score>=80).sort((x,y)=>y.score-x.score);if(shuffle)a.sort(()=>Math.random()-.5);a=a.slice(0,12);$('featured').innerHTML=a.map(featureCard).join('');hydrateHero(a)}
function hydrateHero(items){let hv=$('heroVisual');hv.querySelectorAll('.heroArt').forEach(x=>x.remove());for(const p of items.slice(0,4)){let a=artUrl(p);if(!a)continue;let im=document.createElement('img');im.className='heroArt '+(p.lang==='فارسی'?'lang-fa':'lang-en');im.alt=p.title;im.hidden=true;im.onload=()=>im.hidden=false;im.onerror=()=>im.remove();im.src=a;hv.appendChild(im)}}
function card(p){let s=S(p.id),fa=p.lang==='فارسی',lc=fa?'lang-fa':'lang-en';return `<article class="card ${lc}" dir="${fa?'rtl':'ltr'}"><div class="cover"><span class="langFlag">${fa?'FA':'EN'}</span>${artMarkup(p)}<div class="coverShade"></div><span class="coverMatch">${p.score}% Match</span><button class="favFloat ${s.favorite?'fav':''}" onclick="set('${p.id}',{favorite:${!s.favorite}})">♥</button></div><div class="cardBody"><div class="badges"><span class="badge langBadge">${esc(p.lang)}</span><span class="badge">${esc(p.category)}</span>${(p.tags||[]).slice(0,2).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.level)} • ${esc(p.rating)}</div><p class="desc">${esc(p.desc)}</p>${sourceBlock(p,fa)}<div class="why"><b>${fa?'چرا مناسب است؟':'Why it fits:'}</b><br>${esc(p.why)}</div><div class="progress"><small>${fa?'پیشرفت':'Progress'}: ${s.progress}%</small><input type="range" min="0" max="100" step="5" value="${s.progress}" onchange="set('${p.id}',{progress:+this.value})"></div><div class="actions"><a class="open" target="_blank" rel="noopener" href="${esc(p.url)}">🎙️ ${fa?'باز کردن':'Open'}</a><button onclick="document.getElementById('n-${p.id}').classList.toggle('open')">📝</button></div><div class="note ${s.note?'open':''}" id="n-${p.id}"><textarea id="t-${p.id}" placeholder="یادداشت...">${esc(s.note)}</textarea><button onclick="set('${p.id}',{note:document.getElementById('t-${p.id}').value})">ذخیره</button> <button onclick="set('${p.id}',{listened:true,progress:100})">✓ شنیده شد</button></div></div></article>`}
function render(){let q=$('q').value.toLowerCase(),la=$('lang').value,ca=$('cat').value,st=$('state').value;let a=P.filter(p=>{let s=S(p.id),m=META[p.id]||{},b=[p.title,p.category,p.desc,p.why,p.learningPath,m.description,...(p.tags||[])].join(' ').toLowerCase();return(!q||b.includes(q))&&(!la||p.lang===la)&&(!ca||p.category===ca)&&(!tag||(p.tags||[]).includes(tag))&&(!st||(st==='fav'&&s.favorite)||(st==='done'&&(s.listened||s.progress===100))||(st==='notes'&&s.note))});a.sort((x,y)=>y.score-x.score);$('grid').innerHTML=a.map(card).join('');$('count').textContent=`${a.length} پادکست از ${P.length}`}
$('cat').innerHTML+=[...new Set(P.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fa')).map(x=>`<option>${esc(x)}</option>`).join('');['q','lang','cat','state'].forEach(x=>$(x).addEventListener('input',render));let tags=['Cybersecurity','Microsoft','Electronics','3D Printing','Storytelling','True Crime','Music','AI'];$('chips').innerHTML='<button class="chip active" data-t="">همه</button>'+tags.map(x=>`<button class="chip" data-t="${x}">${x}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');tag=b.dataset.t;render()});
document.documentElement.dataset.theme=localStorage.getItem('atlasTheme')||'dark';$('theme').onclick=()=>{let n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('atlasTheme',n)};$('backup').onclick=()=>{let b=new Blob([JSON.stringify(U,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='soheil-podcast-backup.json';a.click()};$('restore').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{U=JSON.parse(r.result);save();render();paths();next()}catch{alert('فایل معتبر نیست')}};r.readAsText(f)};$('refreshFeatured').onclick=()=>featured(true);$('shuffle').onclick=()=>{let p=P[Math.floor(Math.random()*P.length)];window.open(p.url,'_blank')};stats();paths();categories();next();featured();render();