const P=window.PODCASTS||[],K='soheilPodcastAtlasV4',AK='atlasArtworkV6_2';
let U=JSON.parse(localStorage.getItem(K)||'{}'),ART=JSON.parse(localStorage.getItem(AK)||'{}'),tag='';
const $=x=>document.getElementById(x),S=id=>U[id]||{favorite:false,listened:false,progress:0,note:''};
function save(){localStorage.setItem(K,JSON.stringify(U));stats()}
function set(id,p){U[id]={...S(id),...p};save();render();paths();next()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function stats(){let s=P.map(p=>S(p.id));$('total').textContent=P.length;$('favN').textContent=s.filter(x=>x.favorite).length;$('doneN').textContent=s.filter(x=>x.listened||x.progress===100).length;$('avgN').textContent=Math.round(s.reduce((a,x)=>a+(x.progress||0),0)/Math.max(1,s.length))+'%'}
function normalize(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function titleQuery(p){return p.title.replace(/[|｜]/g,' ').replace(/\s+/g,' ').trim()}
function titleScore(a,b){a=normalize(a);b=normalize(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .88;let A=new Set(a.split(' ').filter(x=>x.length>1)),B=new Set(b.split(' ').filter(x=>x.length>1)),hit=[...A].filter(x=>B.has(x)).length;return hit/Math.max(A.size,B.size,1)}
function artworkUrl(r){let u=r&&(r.artworkUrl600||r.artworkUrl100||r.artworkUrl60);if(!u)return'';u=u.replace(/^http:/,'https:');return u.replace(/\/\d+x\d+bb(?=[.-])/,'/600x600bb')}
function langClass(p){return p.lang==='فارسی'||(p.tags||[]).includes('Persian')?'lang-fa':'lang-en'}
function queryVariants(p){let raw=String(p.title||'').trim(),parts=raw.split(/[|｜—–:-]/).map(x=>x.trim()).filter(x=>x.length>2),latin=(raw.match(/[A-Za-z][A-Za-z0-9'’ .&+-]{2,}/g)||[]).join(' ').trim(),fa=(raw.match(/[\u0600-\u06FF][\u0600-\u06FF\s‌‍-]{2,}/g)||[]).join(' ').trim(),out=[raw,titleQuery(p),...parts,latin,fa];return [...new Set(out.map(x=>x.replace(/\s+/g,' ').trim()).filter(x=>x.length>2))].slice(0,6)}
let cbSeq=0;
function jsonp(url,timeout=12000){return new Promise((resolve,reject)=>{let cb='__atlas_cb_'+(++cbSeq),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('timeout')),timeout);function done(err,data){clearTimeout(timer);try{delete window[cb]}catch{}s.remove();err?reject(err):resolve(data)}window[cb]=d=>done(null,d);s.onerror=()=>done(new Error('network'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.head.appendChild(s)})}
const inflight=new Map();
async function resolveArtwork(p){if(p.artwork||p.cover||p.image)return{img:p.artwork||p.cover||p.image,direct:true};if(ART[p.id]&&ART[p.id].img)return ART[p.id];if(ART[p.id]&&ART[p.id].miss&&Date.now()-(ART[p.id].ts||0)<1800000)return ART[p.id];if(inflight.has(p.id))return inflight.get(p.id);let task=(async()=>{let best=null,score=0;try{for(let q of queryVariants(p)){for(let country of ['us','au','gb','ca']){let url='https://itunes.apple.com/search?media=podcast&entity=podcast&limit=25&country='+country+'&term='+encodeURIComponent(q);let d;try{d=await jsonp(url,9000)}catch{continue}for(let r of d.results||[]){let n=r.collectionName||r.trackName||'',img=artworkUrl(r),s=Math.max(titleScore(p.title,n),titleScore(q,n));if(img&&s>score){score=s;best=r}}if(best&&score>=.72)break}if(best&&score>=.72)break}if(best&&score>=.28){let img=artworkUrl(best);if(img){let v={img,apple:best.collectionViewUrl||best.trackViewUrl||'',matched:best.collectionName||best.trackName||'',score};ART[p.id]=v;localStorage.setItem(AK,JSON.stringify(ART));return v}}}catch(e){console.warn('Artwork lookup failed:',p.title,e)}ART[p.id]={miss:true,ts:Date.now()};localStorage.setItem(AK,JSON.stringify(ART));return ART[p.id]})();inflight.set(p.id,task);try{return await task}finally{inflight.delete(p.id)}}
function showArtwork(img,url,p){return new Promise(resolve=>{let fallback=img.parentElement?.querySelector('.coverFallback');img.onload=()=>{img.hidden=false;if(fallback)fallback.hidden=true;resolve(true)};img.onerror=()=>{img.hidden=true;if(fallback)fallback.hidden=false;if(p&&ART[p.id]){delete ART[p.id];localStorage.setItem(AK,JSON.stringify(ART))}resolve(false)};img.referrerPolicy='no-referrer';img.decoding='async';img.src=url})}
async function hydrateImg(img,p){if(!img||!p||img.dataset.loading)return;img.dataset.loading='1';let a=await resolveArtwork(p);if(a&&a.img)await showArtwork(img,a.img,p);img.dataset.loading=''}
function setupLazyArtwork(root=document){let imgs=[...root.querySelectorAll('img[data-art-id]')];if(!('IntersectionObserver'in window)){imgs.forEach(i=>hydrateImg(i,P.find(p=>p.id===i.dataset.artId)));return}let ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let i=e.target,p=P.find(x=>x.id===i.dataset.artId);if(p)hydrateImg(i,p);ob.unobserve(i)}}),{rootMargin:'700px'});imgs.forEach(i=>ob.observe(i))}
function next(){let x=P.map(p=>({p,s:S(p.id)})).filter(x=>!x.s.listened&&x.s.progress<100).sort((a,b)=>(b.p.score+(b.s.favorite?30:0)+b.s.progress)-(a.p.score+(a.s.favorite?30:0)+a.s.progress))[0];if(!x){$('next').innerHTML='همه موارد تکمیل شده‌اند.';return}$('next').className='next '+langClass(x.p);$('next').innerHTML=`<div class="nextArt"><img data-art-id="${x.p.id}" hidden alt="${esc(x.p.title)}"><div class="coverFallback">${esc(x.p.icon||'🎙️')}</div></div><div><b>${esc(x.p.title)}</b><br><span>${esc(x.p.category)} • ${x.p.score}% Match • ${x.s.progress}% پیشرفت</span><br><a target="_blank" rel="noopener" href="${esc(x.p.url)}">باز کردن پادکست</a></div>`;hydrateImg($('next').querySelector('img'),x.p)}
const L=[['Cyber & Microsoft Security','🛡️'],['Maker Lab','🔧'],['Stories & Fiction','📖'],['True Crime','🕵️'],['Music Journey','🎵'],['AI & Future Tech','🤖']];
function paths(){$('paths').innerHTML=L.map(([n,i])=>{let a=P.filter(p=>p.learningPath===n),v=a.length?Math.round(a.reduce((z,p)=>z+(S(p.id).progress||0),0)/a.length):0;return `<div class="path" onclick="filterPath('${n}')"><span style="font-size:25px">${i}</span><strong>${n}</strong><small>${a.length} پادکست • ${v}%</small><div class="bar"><i style="width:${v}%"></i></div></div>`}).join('')}
function filterPath(n){$('q').value=n;tag='';render();$('library').scrollIntoView({behavior:'smooth'})}
const CATS=[['Cybersecurity','🛡️','Cybersecurity & Cloud'],['Electronics','⚡','Electronics & Maker'],['3D Printing','🖨️','3D Printing'],['Storytelling','📚','Stories & Fiction'],['True Crime','🕵️','True Crime'],['Music','🎸','Music'],['Microsoft','☁️','Microsoft'],['AI','🤖','AI & Future Tech']];
function categories(){$('categoryTiles').innerHTML=CATS.map(([t,i,n],k)=>`<div class="categoryTile ct${k%6}" data-icon="${i}" onclick="pickTag('${t}')"><strong>${n}</strong><small>${P.filter(p=>(p.tags||[]).includes(t)).length} انتخاب</small></div>`).join('')}
function pickTag(t){tag=t;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.t===t));render();$('library').scrollIntoView({behavior:'smooth'})}
function featureCard(p){return `<a class="featureCard ${langClass(p)}" dir="${langClass(p)==='lang-fa'?'rtl':'ltr'}" target="_blank" rel="noopener" href="${esc(p.url)}"><div class="featureArtWrap"><img class="featureArt" data-art-id="${p.id}" hidden alt="${esc(p.title)}"><div class="coverFallback">${esc(p.icon||'🎙️')}</div><span class="langFlag">${langClass(p)==='lang-fa'?'FA':'EN'}</span></div><div class="featureMeta"><strong>${esc(p.title)}</strong><small>${esc(p.category)} • ${p.score}%</small></div></a>`}
function featured(shuffle=false){let a=P.filter(p=>p.score>=80).sort((x,y)=>y.score-x.score);if(shuffle)a.sort(()=>Math.random()-.5);a=a.slice(0,12);$('featured').innerHTML=a.map(featureCard).join('');setupLazyArtwork($('featured'));hydrateHero(a)}
async function hydrateHero(items){let hv=$('heroVisual');hv.querySelectorAll('.heroArt').forEach(x=>x.remove());for(let p of items.slice(0,4)){let a=await resolveArtwork(p);if(a&&a.img){let im=document.createElement('img');im.className='heroArt '+langClass(p);im.alt=p.title;im.referrerPolicy='no-referrer';im.onerror=()=>im.remove();im.src=a.img;hv.appendChild(im)}}}
function card(p){let s=S(p.id),fa=p.lang==='فارسی'||(p.tags||[]).includes('Persian'),lc=fa?'lang-fa':'lang-en';return `<article class="card ${lc}" dir="${fa?'rtl':'ltr'}"><div class="cover"><div class="coverFallback">${esc(p.icon||'🎙️')}</div><img data-art-id="${p.id}" hidden alt="${esc(p.title)}" loading="lazy"><div class="coverShade"></div><span class="langFlag">${fa?'FA':'EN'}</span><span class="coverMatch">${p.score}% Match</span><button class="favFloat ${s.favorite?'fav':''}" onclick="set('${p.id}',{favorite:${!s.favorite}})">♥</button></div><div class="cardBody"><div class="badges"><span class="badge langBadge">${esc(p.lang)}</span><span class="badge">${esc(p.category)}</span>${(p.tags||[]).slice(0,3).map(t=>`<span class="badge">${esc(t)}</span>`).join('')}</div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.level)} • ${esc(p.rating)}</div><p class="desc">${esc(p.desc)}</p><div class="why"><b>${fa?'چرا مناسب است؟':'Why it fits:'}</b><br>${esc(p.why)}</div><div class="progress"><small>${fa?'پیشرفت':'Progress'}: ${s.progress}%</small><input type="range" min="0" max="100" step="5" value="${s.progress}" onchange="set('${p.id}',{progress:+this.value})"></div><div class="actions"><a class="open" target="_blank" rel="noopener" href="${esc(p.url)}">🎙️ ${fa?'باز کردن':'Open'}</a><button onclick="document.getElementById('n-${p.id}').classList.toggle('open')">📝</button></div><div class="note ${s.note?'open':''}" id="n-${p.id}"><textarea id="t-${p.id}" placeholder="${fa?'یادداشت...':'Notes...'}">${esc(s.note)}</textarea><button onclick="set('${p.id}',{note:document.getElementById('t-${p.id}').value})">${fa?'ذخیره':'Save'}</button> <button onclick="set('${p.id}',{listened:true,progress:100})">✓ ${fa?'شنیده شد':'Listened'}</button></div></div></article>`}
function render(){let q=$('q').value.toLowerCase(),la=$('lang').value,ca=$('cat').value,st=$('state').value;let a=P.filter(p=>{let s=S(p.id),b=[p.title,p.category,p.desc,p.why,p.learningPath,...(p.tags||[])].join(' ').toLowerCase();return(!q||b.includes(q))&&(!la||p.lang===la)&&(!ca||p.category===ca)&&(!tag||(p.tags||[]).includes(tag))&&(!st||(st==='fav'&&s.favorite)||(st==='done'&&(s.listened||s.progress===100))||(st==='notes'&&s.note))});a.sort((x,y)=>y.score-x.score);$('grid').innerHTML=a.map(card).join('');$('count').textContent=`${a.length} پادکست از ${P.length}`;setupLazyArtwork($('grid'))}
$('cat').innerHTML+=[...new Set(P.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fa')).map(x=>`<option>${esc(x)}</option>`).join('');
['q','lang','cat','state'].forEach(x=>$(x).addEventListener('input',render));
let tags=['Cybersecurity','Microsoft','Electronics','3D Printing','Storytelling','True Crime','Music','AI'];$('chips').innerHTML='<button class="chip active" data-t="">همه</button>'+tags.map(x=>`<button class="chip" data-t="${x}">${x}</button>`).join('');
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');tag=b.dataset.t;render()});
document.documentElement.dataset.theme=localStorage.getItem('atlasTheme')||'dark';$('theme').onclick=()=>{let n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('atlasTheme',n)};
$('backup').onclick=()=>{let b=new Blob([JSON.stringify(U,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='soheil-podcast-backup.json';a.click()};
$('restore').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{U=JSON.parse(r.result);save();render();paths();next()}catch{alert('فایل معتبر نیست')}};r.readAsText(f)};
$('refreshFeatured').onclick=()=>featured(true);$('shuffle').onclick=()=>{let p=P[Math.floor(Math.random()*P.length)];window.open(p.url,'_blank')};
let dp=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();dp=e;$('install').hidden=false});$('install').onclick=async()=>{if(dp){dp.prompt();await dp.userChoice;dp=null;$('install').hidden=true}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
stats();paths();categories();next();featured();render();