window.PODCASTS = [
  {
    "lang": "فارسی",
    "category": "امنیت سایبری",
    "title": "لایه هفتم",
    "level": "همه سطوح",
    "rating": "پیشنهاد ویژه",
    "url": "https://podcast.app/lyh-hftm-p6056036",
    "desc": "پادکستی فارسی درباره فیلترینگ، دسترسی به اینترنت، امنیت دیجیتال شهروندان، حملات سایبری و موضوعات مرتبط با حریم خصوصی و دفاع سایبری.",
    "why": "مستقیم‌ترین گزینه فارسی برای علاقه تو به امنیت سایبری و امنیت دیجیتال.",
    "icon": "🛡️",
    "id": "pod-001",
    "tags": ["Cybersecurity", "Security", "Persian"],
    "score": 90,
    "coverGradient": 1,
    "learningPath": "Cyber & Microsoft Security"
  },
  {
    "lang": "فارسی",
    "category": "امنیت و فناوری اطلاعات",
    "title": "پادفن البرز",
    "level": "مقدماتی تا متوسط",
    "rating": "بسیار مرتبط",
    "url": "https://podcast.app/pdfn-lbrz-p6302098",
    "desc": "اپیزودهای آموزشی و خبری درباره لینوکس، هک و امنیت، برنامه‌نویسی، هوش مصنوعی، بلاک‌چین و اخبار فناوری اطلاعات ایران.",
    "why": "ترکیب مناسبی از امنیت، لینوکس و برنامه‌نویسی دارد.",
    "icon": "🛡️",
    "id": "pod-002",
    "tags": ["Cybersecurity", "Security", "Persian"],
    "score": 90,
    "coverGradient": 2,
    "learningPath": "Cyber & Microsoft Security"
  },
  {
    "lang": "فارسی",
    "category": "فناوری و امنیت",
    "title": "Zero Degrees | صفر درجه",
    "level": "همه سطوح",
    "rating": "منتخب",
    "url": "https://podcast.app/zero-degrees-p6419345",
    "desc": "گفت‌وگو با کارشناسان علم و فناوری، به‌خصوص در حوزه هوش مصنوعی، علوم اعصاب، امنیت و نوآوری‌های تکنولوژیک.",
    "why": "برای دنبال‌کردن دیدگاه‌های گسترده‌تر درباره امنیت و آینده فناوری مناسب است.",
    "icon": "🛡️",
    "id": "pod-003",
    "tags": ["Cybersecurity", "Security", "Persian"],
    "score": 70,
    "coverGradient": 3,
    "learningPath": "Cyber & Microsoft Security"
  },
  {
    "lang": "فارسی",
    "category": "تکنولوژی",
    "title": "خورشت تکنولوژی",
    "level": "همه سطوح",
    "rating": "محبوب",
    "url": "https://podcast.app/khoresht-e-tech-khwrsht-tkhnwlwjy-p405219",
    "desc": "پادکست هفتگی فارسی درباره گجت‌ها، نوآوری‌های جدید، اخبار داغ فناوری و موضوعات محبوب فضای دیجیتال.",
    "why": "برای مرور عمومی و قابل‌فهم اخبار و ابزارهای تکنولوژی.",
    "icon": "🎙️",
    "id": "pod-004",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 4,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "برنامه‌نویسی و فناوری",
    "title": "آنکات فارسی | UncutFarsi",
    "level": "متوسط تا حرفه‌ای",
    "rating": "منتخب",
    "url": "https://podcast.app/ankht-frsy-uncutfarsi-p2435209",
    "desc": "گفت‌وگو درباره تجربه‌های واقعی برنامه‌نویسی، معماری نرم‌افزار، میکروسرویس‌ها، هوش مصنوعی، مسیر شغلی و کار در صنعت فناوری.",
    "why": "مناسب برای تجربه‌های واقعی توسعه نرم‌افزار و فضای حرفه‌ای فناوری.",
    "icon": "🎙️",
    "id": "pod-005",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 5,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "برنامه‌نویسی و متن‌باز",
    "title": "EdiCodes | ادی‌کدز",
    "level": "مقدماتی تا حرفه‌ای",
    "rating": "منتخب",
    "url": "https://podcast.app/edicodes-drys-rnjbr-p1474933",
    "desc": "درباره توسعه نرم‌افزار، فریلنسری، ساخت استارتاپ، متن‌باز، لینوکس، هوش مصنوعی و برنامه‌نویسی در عصر AI.",
    "why": "به علایق تو در لینوکس، اتوماسیون، برنامه‌نویسی و پروژه‌های عملی نزدیک است.",
    "icon": "🎙️",
    "id": "pod-006",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 6,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "برنامه‌نویسی",
    "title": "راکت‌کست",
    "level": "مقدماتی تا متوسط",
    "rating": "کاربردی",
    "url": "https://podcast.app/amwzsh-brnmh-nwysy-rkht-khst-p1706181",
    "desc": "پادکستی فارسی درباره برنامه‌نویسی، طراحی نرم‌افزار، ابزارها و فریم‌ورک‌های جدید.",
    "why": "برای یادگیری مفاهیم توسعه و آشنایی با ابزارهای تازه مناسب است.",
    "icon": "🎙️",
    "id": "pod-007",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 7,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "هوش مصنوعی و آینده فناوری",
    "title": "دنیای تکنولوژی",
    "level": "همه سطوح",
    "rating": "جدید",
    "url": "https://podcast.app/dnyy-tkhnwlwjy-p6399054",
    "desc": "بررسی هوش مصنوعی، یادگیری ماشین، کلان‌داده، آینده کار و اثرات فناوری‌های مدرن بر جامعه.",
    "why": "برای دنبال‌کردن AI و آینده فناوری به زبان فارسی.",
    "icon": "🤖",
    "id": "pod-008",
    "tags": ["AI", "Persian"],
    "score": 60,
    "coverGradient": 0,
    "learningPath": "AI & Future Tech"
  },
  {
    "lang": "فارسی",
    "category": "علم، AI و کارآفرینی",
    "title": "The Science and Success Podcast | علم و موفقیت",
    "level": "همه سطوح",
    "rating": "گفت‌وگومحور",
    "url": "https://podcast.app/the-science-and-success-podcast-pdkhst-lm-w-mwfqyt-p6194003",
    "desc": "گفت‌وگو با پژوهشگران، متخصصان و کارآفرینان ایرانی درباره علم، فناوری، مهندسی، داده، هوش مصنوعی و مسیرهای حرفه‌ای.",
    "why": "برای ترکیب علایق فنی با تجربه‌های واقعی متخصصان ایرانی.",
    "icon": "🤖",
    "id": "pod-009",
    "tags": ["AI", "Persian"],
    "score": 60,
    "coverGradient": 1,
    "learningPath": "AI & Future Tech"
  },
  {
    "lang": "فارسی",
    "category": "فناوری و کسب‌وکار",
    "title": "رشدینو",
    "level": "همه سطوح",
    "rating": "محبوب",
    "url": "https://podcast.app/rdyw-rshdynw-hkh-rshd-y-bzryby-nwyn-roshdino-podcast-p551027",
    "desc": "تحلیل فناوری، هوش مصنوعی، اقتصاد، استارتاپ‌ها، ابزارهای رشد و گفت‌وگو با افراد اثرگذار.",
    "why": "برای علاقه تو به راه‌اندازی SL Forge و پیوند فناوری با کسب‌وکار.",
    "icon": "🎙️",
    "id": "pod-010",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 2,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "الگوریتم و نرم‌افزار",
    "title": "Algulorithm | الگولوریتم",
    "level": "مقدماتی تا متوسط",
    "rating": "آموزشی",
    "url": "https://podcast.app/algulorithm-podcast-pdkhst-lgwlwrytm-p6430550",
    "desc": "پادکست آموزشی درباره برنامه‌نویسی، الگوریتم‌ها و تکنولوژی نرم‌افزار.",
    "why": "برای تقویت پایه‌های فکری برنامه‌نویسی و حل مسئله.",
    "icon": "🎙️",
    "id": "pod-011",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 3,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "تکنولوژی و برنامه‌نویسی",
    "title": "پادکست هشتگ | HashtagCast",
    "level": "مقدماتی",
    "rating": "ساده و روان",
    "url": "https://podcast.app/pdkhst-hshtg-hashtagcast-p908907",
    "desc": "توضیح موضوعات مرتبط با دنیای تکنولوژی به زبان ساده و قابل‌فهم.",
    "why": "برای آشنایی سریع با موضوعات جدید بدون پیچیدگی زیاد.",
    "icon": "🎙️",
    "id": "pod-012",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 4,
    "learningPath": "General Technology"
  },
  {
    "lang": "فارسی",
    "category": "علم و مهندسی",
    "title": "رادیو چرخ",
    "level": "همه سطوح",
    "rating": "آموزشی",
    "url": "https://podcast.app/pdkhst-frsy-rdyw-chrkh-radio-charkh-p1143054",
    "desc": "هر اپیزود حاصل جست‌وجو در بخشی از دنیای علم، تکنولوژی و مهندسی است.",
    "why": "برای علاقه گسترده تو به ساخت، مهندسی و یادگیری فنی.",
    "icon": "🎙️",
    "id": "pod-013",
    "tags": ["Persian"],
    "score": 60,
    "coverGradient": 5,
    "learningPath": "General Technology"
  }
];
