window.PODCASTS.push(...[
  {"lang":"English","category":"Electronics, Arduino & 3D Printing","title":"Hackaday Podcast","level":"Intermediate to Advanced","rating":"Top Pick","url":"https://podcast.app/hackaday-podcast-p590022","desc":"Weekly exploration of hardware hacking, circuit boards, robots, software, 3D printing, machine tools and inventive maker projects.","why":"Probably the single best overall match for your electronics, ESP32, Arduino and 3D-printing interests.","icon":"🔧","id":"pod-014","tags":["Electronics","Maker","Arduino","3D Printing","English"],"score":90,"coverGradient":6,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Electronics & Embedded Systems","title":"The Spark Gap","level":"Intermediate to Advanced","rating":"Highly Relevant","url":"https://podcast.app/the-spark-gap-p7827","desc":"Embedded electronics from practical design details to higher-level engineering discussions, including 3D printing and CNC.","why":"Strong fit for deeper embedded-systems and electronics knowledge.","icon":"🔧","id":"pod-015","tags":["Electronics","Maker","English"],"score":90,"coverGradient":7,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Electronics, Arduino & DIY","title":"The Simple Electronics Podcast","level":"Beginner to Intermediate","rating":"Practical","url":"https://podcast.app/the-simple-electronics-podcast-p1553658","desc":"A friendly hobby-electronics show covering Arduino, soldering, 3D printers and maker projects with different guests.","why":"Approachable and closely aligned with hands-on workshop projects.","icon":"🔧","id":"pod-016","tags":["Electronics","Maker","Arduino","English"],"score":70,"coverGradient":0,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Arduino, Raspberry Pi & 3D Printing","title":"Ham Radio Workbench Podcast","level":"Intermediate","rating":"Deep Dive","url":"https://podcast.app/ham-radio-workbench-podcast-p404846","desc":"A technical maker podcast covering electronics, test equipment, PCB design, Arduino, Raspberry Pi, 3D printing and radio projects.","why":"Excellent for test equipment, diagnostics and practical electronics.","icon":"🔧","id":"pod-017","tags":["Electronics","Maker","Arduino","3D Printing","English"],"score":70,"coverGradient":1,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Maker Movement","title":"That Maker Show","level":"Beginner to Intermediate","rating":"Broad","url":"https://podcast.app/that-maker-show-p79310","desc":"Maker news and projects spanning 3D printing, printable electronics, Arduino and Raspberry Pi.","why":"Good broad maker coverage with direct relevance to your hobby projects.","icon":"🔧","id":"pod-018","tags":["Electronics","Maker","English"],"score":70,"coverGradient":2,"learningPath":"Maker Lab"},
  {"lang":"English","category":"3D Printing","title":"The Infill Podcast","level":"All Levels","rating":"3D Printing Pick","url":"https://podcast.app/the-infill-podcast-the-place-for-3d-printing-p6035878","desc":"A weekly interview show focused on 3D printing, additive manufacturing and maker culture.","why":"Dedicated 3D-printing coverage for printers, materials, workflows and industry trends.","icon":"🔧","id":"pod-019","tags":["Electronics","Maker","3D Printing","English"],"score":70,"coverGradient":3,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Makers & Fabrication","title":"Maker Talk Podcast","level":"All Levels","rating":"Workshop","url":"https://podcast.app/maker-talk-podcast-p919925","desc":"Conversations about woodworking, metalworking, electronics, 3D printing and building things.","why":"Useful for combining electronics and 3D-printed enclosures or workshop builds.","icon":"🔧","id":"pod-020","tags":["Electronics","Maker","English"],"score":70,"coverGradient":4,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Maker Stories","title":"The Make or Break Show","level":"All Levels","rating":"Inspiring","url":"https://podcast.app/the-make-or-break-show-p390369","desc":"Interviews with makers about what they build and what they learn when projects fail, across electronics, 3D printing, wood and metal.","why":"Good for practical lessons, creative motivation and SL Forge ideas.","icon":"🔧","id":"pod-021","tags":["Electronics","Maker","Storytelling","English"],"score":75,"coverGradient":5,"learningPath":"Maker Lab"},
  {"lang":"English","category":"Microsoft Security","title":"The Microsoft Security Insights Show","level":"Intermediate to Advanced","rating":"Top Pick","url":"https://podcast.app/the-microsoft-security-insights-show-p1047414","desc":"News, guidance and practical discussion around Microsoft Sentinel, Microsoft 365 Defender, Azure security and AI.","why":"Directly aligned with your professional Microsoft security work.","icon":"🛡️","id":"pod-022","tags":["Cybersecurity","Security","Microsoft","Azure","M365","English"],"score":90,"coverGradient":6,"learningPath":"Cyber & Microsoft Security"},
  {"lang":"English","category":"Microsoft 365 & Cybersecurity","title":"Practical 365 Podcast","level":"Intermediate to Advanced","rating":"Professional","url":"https://podcast.app/practical-365-podcast-microsoft-365-copilot-cybersecurity-news-discussions-p944806","desc":"Microsoft MVPs discuss Microsoft 365, Copilot, Teams, Exchange, cybersecurity and real-world enterprise implementation.","why":"Very useful for Microsoft 365, Exchange, security and tenant operations.","icon":"🎙️","id":"pod-023","tags":["Cybersecurity","Security","Microsoft","Azure","M365","English"],"score":70,"coverGradient":7,"learningPath":"Cyber & Microsoft Security"},
  {"lang":"English","category":"Microsoft Security","title":"Talking Security","level":"Intermediate","rating":"Focused","url":"https://podcast.app/talking-security-for-news-about-items-related-to-microsoft-security-p907036","desc":"Guest discussions and news primarily focused on Microsoft security technologies.","why":"A focused companion for Defender, Sentinel and Microsoft security updates.","icon":"🛡️","id":"pod-024","tags":["Cybersecurity","Security","Microsoft","Azure","M365","English"],"score":70,"coverGradient":0,"learningPath":"Cyber & Microsoft Security"},
  {"lang":"English","category":"Cloud Security","title":"Cloud Security Podcast","level":"Intermediate to Advanced","rating":"Top Pick","url":"https://podcast.app/cloud-security-podcast-p911968","desc":"Practical, provider-neutral conversations with security experts about AWS, Azure, Google Cloud and AI security at scale.","why":"Strong for expanding beyond Microsoft while keeping cloud-security depth.","icon":"🛡️","id":"pod-025","tags":["Cybersecurity","Security","English"],"score":90,"coverGradient":1,"learningPath":"Cyber & Microsoft Security"},
  {"lang":"English","category":"AI Security","title":"AI Security Podcast","level":"Advanced","rating":"Emerging Field","url":"https://podcast.app/ai-security-podcast-p6026879","desc":"Practical discussions for CISOs and security leaders about securing AI systems and using AI in cybersecurity.","why":"Connects your cybersecurity background with rapidly growing AI-security risks.","icon":"🛡️","id":"pod-026","tags":["Cybersecurity","Security","AI","English"],"score":70,"coverGradient":2,"learningPath":"Cyber & Microsoft Security"}
]);
