window.PODCASTS.push(...[
{"lang":"فارسی","category":"موسیقی","title":"آلبوم | Album","level":"همه سطوح","rating":"پیشنهاد ویژه","url":"https://podcast.app/album-albwm-p601504","desc":"روایت داستان ساخته‌شدن و انتشار آلبوم‌های تأثیرگذار تاریخ موسیقی.","why":"برای علاقه تو به موسیقی، گیتار و داستان پشت آثار مشهور بسیار مناسب است.","icon":"🎵","id":"pod-040","tags":["Music","Persian"],"score":85,"coverGradient":0,"learningPath":"Music Journey"},
{"lang":"فارسی","category":"موسیقی","title":"مترونوم | Metronom","level":"همه سطوح","rating":"منتخب","url":"https://podcast.app/metronom-mtrwnwm-p570429","desc":"پادکستی درباره موسیقی ایرانی و داستان ساخته‌شدن ترانه‌های مشهور.","why":"بهترین ترکیب تاریخ موسیقی ایرانی و قصه پشت ترانه‌ها.","icon":"🎵","id":"pod-041","tags":["Music","Persian"],"score":65,"coverGradient":1,"learningPath":"Music Journey"},
{"lang":"فارسی","category":"موسیقی","title":"کُرُن | Koron","level":"همه سطوح","rating":"تخصصی","url":"https://podcast.app/koron-khurun-p439159","desc":"پادکستی درباره موسیقی ایران، هنرمندان، آثار و موضوعات مرتبط با موسیقی ایرانی.","why":"برای شناخت عمیق‌تر موسیقی ایران.","icon":"🎵","id":"pod-042","tags":["Music","Persian"],"score":65,"coverGradient":2,"learningPath":"Music Journey"},
{"lang":"فارسی","category":"موسیقی","title":"پلی‌لیست | PlayList","level":"همه سطوح","rating":"شنیدنی","url":"https://podcast.app/ply-lyst-playlist-p1050921","desc":"مجموعه‌هایی از موسیقی با پیوند مشترک در سبک، هنرمند، دوره تاریخی، مود یا موضوع.","why":"برای کشف موسیقی و ساختن حال‌وهوای شنیداری مختلف.","icon":"🎵","id":"pod-043","tags":["Music","Persian"],"score":65,"coverGradient":3,"learningPath":"Music Journey"},
{"lang":"English","category":"True Stories","title":"This American Life","level":"Intermediate English","rating":"World Famous","url":"https://podcast.app/this-american-life-p2","desc":"True stories that unfold like short radio films, mixing personal lives, humour, emotion, journalism and surprising turns.","why":"One of the strongest English-language storytelling podcasts ever made.","icon":"📖","id":"pod-044","tags":["Storytelling","English"],"score":65,"coverGradient":4,"learningPath":"Stories & Fiction"},
{"lang":"English","category":"Short Fiction","title":"LeVar Burton Reads","level":"Intermediate English","rating":"Top Pick","url":"https://podcast.app/levar-burton-reads-p349239","desc":"Carefully selected short fiction narrated by LeVar Burton with immersive sound design and stories from major authors.","why":"Excellent for short stories, voice performance and immersive listening.","icon":"📖","id":"pod-045","tags":["Storytelling","English"],"score":85,"coverGradient":5,"learningPath":"Stories & Fiction"},
{"lang":"English","category":"Audio Fiction","title":"The Magnus Archives","level":"Advanced English","rating":"Highly Popular","url":"https://podcast.app/the-magnus-archives-p131154","desc":"Award-winning horror audio drama built from short statements, mysteries and an expanding serial plot.","why":"Strong storytelling, atmosphere and long-form mystery.","icon":"📖","id":"pod-046","tags":["Storytelling","English"],"score":65,"coverGradient":6,"learningPath":"Stories & Fiction"},
{"lang":"English","category":"True Crime","title":"Crime Junkie","level":"Intermediate English","rating":"Very Popular","url":"https://podcast.app/crime-junkie-p404845","desc":"Weekly deep dives into infamous and underreported crimes, missing-person cases and unresolved mysteries.","why":"A polished and accessible starting point for English true crime.","icon":"🕵️","id":"pod-047","tags":["True Crime","English"],"score":85,"coverGradient":7,"learningPath":"True Crime"},
{"lang":"English","category":"True Crime","title":"Serial","level":"Intermediate to Advanced","rating":"Genre Classic","url":"https://podcast.app/serial-p1","desc":"Landmark narrative journalism that investigates one story across a season and helped define modern podcasting.","why":"Essential listening for long-form investigative storytelling.","icon":"🕵️","id":"pod-048","tags":["True Crime","English"],"score":65,"coverGradient":0,"learningPath":"True Crime"},
{"lang":"English","category":"True Crime & Mystery","title":"MrBallen Podcast","level":"Intermediate English","rating":"Very Popular","url":"https://podcast.app/mrballen-podcast-strange-dark-mysterious-stories-p3502711","desc":"Strange, dark and mysterious true stories delivered in a dramatic, highly engaging storytelling format.","why":"Fast-paced, cinematic and ideal when you want gripping standalone stories.","icon":"🕵️","id":"pod-049","tags":["True Crime","English"],"score":85,"coverGradient":1,"learningPath":"True Crime"},
{"lang":"English","category":"True Crime","title":"Bear Brook","level":"Advanced English","rating":"Critically Acclaimed","url":"https://podcast.app/bear-brook-p561906","desc":"Deep investigative reporting into cold cases, identity, forensic science and the criminal justice system.","why":"One of the most respected investigative true-crime series.","icon":"🕵️","id":"pod-050","tags":["True Crime","English"],"score":65,"coverGradient":2,"learningPath":"True Crime"},
{"lang":"English","category":"True Crime","title":"Buried Bones","level":"Advanced English","rating":"Forensics","url":"https://podcast.app/buried-bones-a-historical-true-crime-podcast-with-kate-winkler-dawson-and-paul-holes-p673258","desc":"Historical true-crime cases reconsidered with modern forensic knowledge by a journalist and an investigator.","why":"A strong fit if you enjoy evidence, investigation and technical analysis.","icon":"🕵️","id":"pod-051","tags":["True Crime","English"],"score":65,"coverGradient":3,"learningPath":"True Crime"},
{"lang":"English","category":"Music & True Crime","title":"DISGRACELAND","level":"Advanced English","rating":"Unique","url":"https://podcast.app/disgraceland-p383517","desc":"Music history, scandal and true crime told through highly produced scripted stories about famous artists.","why":"A perfect crossover between your interest in music and real crime stories.","icon":"🎵","id":"pod-052","tags":["True Crime","Music","English"],"score":65,"coverGradient":4,"learningPath":"True Crime"}
]);