window.PODCASTS.push(...[
{"lang":"English","category":"AI & Technology","title":"AI Inside","level":"All Levels","rating":"Current","url":"https://podcast.app/ai-inside-p6026878","desc":"Weekly AI news and interviews with researchers and product leaders from major AI labs and technology companies.","why":"A good current overview of AI products, research and industry direction.","icon":"🤖","id":"pod-027","tags":["AI","English"],"score":60,"coverGradient":3,"learningPath":"AI & Future Tech"},
{"lang":"English","category":"Microsoft AI & Governance","title":"Forward Deployed","level":"Intermediate to Advanced","rating":"Enterprise AI","url":"https://podcast.app/forward-deployed-p6018360","desc":"Secure and governed enterprise AI using Microsoft Copilot Studio, Azure AI Foundry, Entra, Purview and Microsoft Security.","why":"Highly relevant to combining Microsoft cloud, AI, security and governance.","icon":"🤖","id":"pod-028","tags":["Microsoft","Azure","M365","AI","English"],"score":70,"coverGradient":4,"learningPath":"Cyber & Microsoft Security"},
{"lang":"English","category":"Sysadmin, Microsoft & PowerShell","title":"Hope This Helps – A Tech Podcast","level":"Intermediate","rating":"Fun + Practical","url":"https://podcast.app/hope-this-helps-a-tech-podcast-p931740","desc":"Sysadmin stories and discussions about cloud, Microsoft 365, Azure, Defender, Exchange, InfoSec, PowerShell and Docker.","why":"A close match for your day-to-day professional toolset and troubleshooting style.","icon":"🎙️","id":"pod-029","tags":["Microsoft","Azure","M365","English"],"score":70,"coverGradient":5,"learningPath":"Cyber & Microsoft Security"},
{"lang":"فارسی","category":"داستان واقعی","title":"ChannelB | چنل‌بی","level":"همه سطوح","rating":"بسیار پرمخاطب","url":"https://podcast.app/channelb-pdkhst-frsy-p160107","desc":"روایت حرفه‌ای و شنیدنی ماجراهای واقعی از منابع معتبر؛ با فضاسازی، تحقیق و داستان‌گویی قوی.","why":"یکی از شناخته‌شده‌ترین پادکست‌های فارسی برای داستان‌های واقعی و بلند.","icon":"📖","id":"pod-030","tags":["Storytelling","Persian"],"score":85,"coverGradient":6,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان واقعی","title":"پادکست آن | On Podcast","level":"همه سطوح","rating":"منتخب","url":"https://podcast.app/on-podcast-pdkhst-an-p604335","desc":"در هر اپیزود داستان واقعی آدم‌ها روایت می‌شود تا شنونده بتواند خودش را جای شخصیت‌های قصه بگذارد.","why":"برای داستان‌های انسانی و واقعی با زاویه دید احساسی و همدلانه.","icon":"📖","id":"pod-031","tags":["Storytelling","Persian"],"score":65,"coverGradient":7,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان واقعی","title":"راوی | Ravi","level":"همه سطوح","rating":"احساسی","url":"https://podcast.app/ravi-pdkhst-frsy-rwy-p861119","desc":"قصه زندگی آدم‌هایی که یک چالش مهم، مسیر زندگی‌شان را شنیدنی و متفاوت کرده است.","why":"مناسب برای شنیدن تجربه‌های واقعی، مستقل و الهام‌بخش.","icon":"📖","id":"pod-032","tags":["Storytelling","Persian"],"score":65,"coverGradient":0,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان و داستان کوتاه","title":"داستان شب","level":"همه سطوح","rating":"پرمخاطب","url":"https://podcast.app/dstn-shb-p550698","desc":"هر شب یک داستان کوتاه برای شنیدن؛ مناسب زمان استراحت، رانندگی و قبل از خواب.","why":"منبع بزرگ و منظم برای داستان‌های کوتاه فارسی.","icon":"📖","id":"pod-033","tags":["Storytelling","Persian"],"score":65,"coverGradient":1,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان و داستان کوتاه","title":"لالالند | LalaLand","level":"همه سطوح","rating":"منتخب","url":"https://podcast.app/lalaland-lllnd-p6106244","desc":"خوانش داستان‌های کوتاه مشهور و شنیدنی از نویسندگان بزرگ جهان؛ هر قصه مستقل است.","why":"برای آشنایی با داستان کوتاه جهان به زبان فارسی.","icon":"📖","id":"pod-034","tags":["Storytelling","Persian"],"score":65,"coverGradient":2,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان و داستان کوتاه","title":"ساعت صفر","level":"همه سطوح","rating":"بسیار پرمخاطب","url":"https://podcast.app/saate-sefr-podcast-pdkhst-st-sfr-p849690","desc":"یک داستان سریالی اورجینال و پرکشش درباره سفر در زمان، دنیاهای موازی و رازهای تاریخی با صداگذاری حرفه‌ای.","why":"برای داستان صوتی سریالی، رمزآلود و سینمایی یکی از بهترین گزینه‌های فارسی است.","icon":"📖","id":"pod-035","tags":["Storytelling","Persian"],"score":85,"coverGradient":3,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"داستان و ادبیات","title":"رادیو دیو","level":"همه سطوح","rating":"هنری","url":"https://podcast.app/radio-deevpdkhst-rdyw-dyw-p529215","desc":"سفرهای خیال‌پردازانه با ترکیب ادبیات و موسیقی دستچین‌شده پیرامون اقلیم‌ها و موضوعات مختلف.","why":"ترکیب بسیار زیبا از داستان، ادبیات، موسیقی و اتمسفر.","icon":"📖","id":"pod-036","tags":["Storytelling","Persian"],"score":65,"coverGradient":4,"learningPath":"Stories & Fiction"},
{"lang":"فارسی","category":"جنایی واقعی","title":"پادکست جنون","level":"بزرگسال","rating":"پرطرفدار","url":"https://podcast.app/pdkhst-jnwn-junoonpodcast-p1531870","desc":"روایت و رمزگشایی پرونده‌های جنایی واقعی جهان و جرائمی که مجرمان تلاش کرده‌اند پنهان کنند.","why":"برای پرونده‌های واقعی، معمایی و تحقیق‌محور.","icon":"🕵️","id":"pod-037","tags":["True Crime","Persian"],"score":65,"coverGradient":5,"learningPath":"True Crime"},
{"lang":"فارسی","category":"جنایی واقعی","title":"فیکشن | Fiction Podcast","level":"بزرگسال","rating":"پرمخاطب","url":"https://podcast.app/pdkhst-frsy-fykhshn-fiction-podcast-p759348","desc":"روایت پرونده‌های جنایی و تروکرایم با تمرکز بر داستان‌گویی و جزئیات پرونده.","why":"یکی از گزینه‌های مطرح فارسی در ژانر True Crime.","icon":"🕵️","id":"pod-038","tags":["True Crime","Persian"],"score":65,"coverGradient":6,"learningPath":"True Crime"},
{"lang":"فارسی","category":"داستان واقعی و تراژدی","title":"رادیو تراژدی","level":"همه سطوح","rating":"تحقیقی","url":"https://podcast.app/radio-tragedy-rdyw-trjdy-p1555363","desc":"داستان زندگی‌های تراژیک با پایه واقعیت و برگرفته از کار روزنامه‌نگاران تحقیقی.","why":"برای داستان‌های واقعی جدی، مستند و اثرگذار.","icon":"📖","id":"pod-039","tags":["Storytelling","Persian"],"score":65,"coverGradient":7,"learningPath":"Stories & Fiction"}
]);